version: '3.7'

services:
  bot:
    build: .
    restart: always
    stop_signal: SIGINT
    volumes:
      - ./logs:/itmo_coffee_project/logs
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: randomcoffeedb_students
    volumes:
      - ./database/postgres/DDL:/docker-entrypoint-initdb.d
      - ./database/postgres/data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: "always"
    ports:
      - "6379:6379"
    volumes:
      - ./database/redis/config:/usr/local/etc/redis
      - ./database/redis/data:/data
    command: "redis-server /usr/local/etc/redis/redis.config --requirepass password"
